/*
# Remove unused generate_receipt_url SQL function

Signed URLs are generated by the admin-subscriptions edge function using
the service role + supabase-js. The SQL version was fragile (no storage
helper available). list_all_subscription_requests is kept but unused for
now — the edge function reads the table directly with the service role.
*/

DROP FUNCTION IF EXISTS public.generate_receipt_url(text);
